version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d appdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  backend:
    build: 
      context: ./app/backend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://app:app@db:5432/appdb?schema=public
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=ambureview-super-secret-jwt-key-2024
      - JWT_EXPIRES_IN=7d
      - PORT=3001
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "3001:3001"
    volumes:
      - ./app/backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./app/frontend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:3001
    depends_on:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ./app/frontend:/app
      - /app/node_modules

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "8025:8025"
      - "1025:1025"

volumes:
  db_data:
